model:
  name: resnet50
  pretrained: IMAGENET1K_V1
  num_classes: 5

training:
  num_epochs: 5
  batch_size: 32
  learning_rate: 0.001
  optimizer: Adam

augmentation:
  resize: 512
  crop_size: 224
  brightness: 0.2
  contrast: 0.2
  
scheduler:
  step_size: 3
  gamma: 0.1
  
data:
  train_test_split: 0.2
  random_state: 42
