model: resnet50
pretrained: IMAGENET1K_V1
batch_size: 32
learning_rate: 0.001
num_epochs: 1
optimizer: Adam
scheduler_step: 3
scheduler_gamma: 0.1
train_test_split: 0.2
image_size: 224
num_classes: 5
